menu:
  Home: /
  Archives: /archives
  RSS: /atom.xml
  About: /about

widgets:
- search
- ads
- weibo
- category
- tag
- adsbottom

excerpt_link: Read More

twitter:
  username: firedragonpzy
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss: /atom.xml

comment_provider: facebook
# Facebook comment
facebook:
  appid: pzy1991@yeah.net
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light